### ISSUE TITLE
self-update command

### ISSUE THREAD

**Issue by jeanmonod** [liip/taxi#112]
Even if we can update with the install.sh script, it would be great if we can just run:

    taxi self-update

The script could tell the current version, tell the last available version and ask for a confirmation

**Comment by sephii** [comment]
Now that the docs recommend installing taxi with pip, I think the upgrade procedure is easier (`pip install --upgrade taxi`). I would close this for now, because implementing a `self-update` command would be very complex if we want to cover all the installation scenarios (installed with pip, installed with a debian package, installed with pipx, etc).
