### ISSUE TITLE
Warning display could be improve

### ISSUE THREAD

**Issue by jeanmonod** [liip/taxi#127]
When I commit my timesheets, sometime I got a warning message. Here is an example:

![image](https://user-images.githubusercontent.com/114489/82022974-d23d2880-968d-11ea-943b-ceecd9c65b45.png)

It's not clear at all if the warning belong to the `_internal` or the `fco_co` activity. Can we improve that?

**Comment by sephii** [comment]
I agree with you, and I already had the exact same problem. ^^ Do you have any suggestion on how to improve this? Putting the line in yellow is not enough because you might have 2 entries with a warning that follow each other. Maybe adding some detail to the message like "There's an issue with the entry below: The project budget is exceeded. Maybe check with your PO"?

**Comment by jeanmonod** [comment]
A first step would be to put the warning after the entry. Maybe with indentation? Like:

    _internal     0.25      Tests
       ↳ The project budget is exceeded
    _internal     0.25      Tests
    _internal     0.25      Tests

**Comment by sephii** [comment]
Fix will be released in the next taxi-zebra version.
