### ISSUE TITLE
Aliases are forced as lower case and projects identifiers to integers

### ISSUE THREAD

**Issue by gnutix** [liip/taxi#129]
@sephii With the taxi-tempo plugin, we can use JIRA tickets as aliases, like `INFRA-5` or `OPS-318`. However, because of how taxi currently works, we're forced to write them in lower case in our timesheet files.

In the same type of issues, the project identifier is forced to be an integer, where I would have used the first part of the JIRA issue ("INFRA"), which lead us to do [quite a hack](https://github.com/alexandreblin/taxi-tempo/blob/master/taxi_tempo/backend.py#L42-L56) to convert it back and forth and therefore the aliases generated in `~/.taxirc` are obfuscated (where they wouldn't need to be).

 Any chance these constraints might be made optional / removed ?

**Comment by sephii** [comment]
Can you describe what's happening when you use a non-lowercase alias? I don't remember any constraint regarding aliases but it's been a long time since I last worked on the parser. ^^

For the project id constraint I wouldn't see a problem accepting an str type. I'd be happy to review a PR, or this will have to wait a bit until I find some time to work on this.

**Comment by gnutix** [comment]
Fixed it! The issue with uppercase aliases in timesheet entries was that it resulted in an "inexistent alias" warning and the entry was skipped.
