### ISSUE TITLE
Allow `taxi start` to be accurate to the minute

### ISSUE THREAD

**Issue by gnutix** [liip/taxi#131]
Rounding time ranges to '00, '15, '30, '45 is a wanted feature for Zebra, as far as I recall.

With tempo, you can log work down to the minute. It would be nice if `taxi start` could be that precise (with an option for zebra to round it up, probably).

**Comment by gnutix** [comment]
I've just noticed that if you run `taxi start` with no previous entries in the day, it *is* accurate to the minute (`taxi start SM-13` @ 21:42 => `SM-13 21:42-? ?`)...

**Comment by sephii** [comment]
Yes, taxi makes sure entries are rounded to 15 minutes not by only accepting 00, 15, 30 and 45 as minutes, but when "completing" an entry. So if you start an entry but you don't have any previously started one, it will be accurate to the minute.

I think it would make sense to use a setting instead of a hardcoded value for the rounding.
