### ISSUE TITLE
[NICE] `taxi stop` handling of the entry's description

### ISSUE THREAD

**Issue by gnutix** [liip/taxi#132]
As taxi requires a description for each entry, I would find it more intuitive that `taxi stop` would require providing a description (interactively would be nice) if it was not already provided on `taxi start` (and even if it was, it should probably ask for a confirmation).

@sephii What do you think ?

**Comment by sephii** [comment]
I'm not in favour of making things unnecessarily mandatory, and I don't really see the point of making the description mandatory in the `stop` command.

The current behaviour is to use `?` as a placeholder when not providing a description in the `start` command to make the file parseable. Sometimes I don't want to think too much about the details when timesheeting, so I just `taxi start` and `taxi stop` without any description, and fill in the blanks when I see some question marks in `taxi status`. Since entries with `?` as a description are ignored, there's no risk of pushing them.

Also forcing to provide a description in the `stop` command if there wasn't any description given would mean also forcing the `start` command to provide a description for any continued entry that doesn't have a description, which could quickly become confusing.

**Comment by gnutix** [comment]
> Since entries with ? as a description are ignored, there's no risk of pushing them.

I wasn't aware of that! Then it's a state that I agree with.
